#!/bin/sh
remote="$1"
url="$2"

zero=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')


while read local_ref local_oid remote_ref remote_oid
do
	if test "$local_oid" = "$zero"
	then
		# do nothing on branch delete
		:
	else
		if test "$remote_oid" = "$zero"
		then
			# New branch, examine all commits
			range="$local_oid"
		else
			# Update to existing branch, examine new commits
			range="$remote_oid..$local_oid"
		fi

    commits=$(git rev-list -n 1 "$range" -- $project_path)

    if [ "$commits" != "" ]
    then
      [ "$project_path" != "" ] && cd $project_path

      $mix_path git_hooks.run $git_hook "$@"

      [ $? -ne 0 ] && exit 1
    fi
	fi
done


exit 0
